# Setup
title: Cho-AH Blog
description: 어제보다 나은 오늘
url: https://likegirl.github.io
avatar: /peng.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - not-pure-poole
	- jemoji

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://twitter.com/vszhub
    - https://github.com/vszhub
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
disqus: likegirl

# Specify the author for blog posts
author:
  name: Songzi Vong
  url: https://github.com/likegirl/
  email: joa89130@gmail.com

# disqus_shortname: 'likegirl'